apiVersion: v2
appVersion: 1.16.0
dependencies:
- name: ckan
  repository: https://raw.githubusercontent.com/datopian/dx-helm-ckan/wri-setup/charts/
  version: v3.1.2-wri
#- name: redis
#  repository: https://charts.bitnami.com/bitnami
#  version: 10.7.4
- name: solr
  repository: https://raw.githubusercontent.com/datopian/ckan-cloud-solr/upgrade/v.1.25/charts/
  version: v1.1.0
description: Vanilla CKAN for R&D purposes
name: vanilla
type: application
version: 0.1.0
