version: 2
updates:
  # npm
  - package-ecosystem: "npm"
    directory: "/deployment/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/e2e-tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "npm"
    directory: "/integration-tests"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    versioning-strategy: "increase-if-necessary"
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      npm-minor-patch:
        update-types:
          - "minor"
          - "patch"

  # pip
  - package-ecosystem: "pip"
    directory: "/datapusher"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/ckan-backend-dev"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/migration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/load-testing"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/prefect-server/jobs/datapusher"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/ckan-backend-dev/src/ckanext-wri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "numpy"
        versions: [">=2.0.0"]
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/ckanext-wri"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
      - dependency-name: "numpy"
        versions: [">=2.0.0"]
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  - package-ecosystem: "pip"
    directory: "/scripts/cost-splitting"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 10
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
    groups:
      pip-minor-patch:
        update-types:
          - "minor"
          - "patch"

  # Docker
  - package-ecosystem: "docker"
    directory: "/ckan-backend-dev"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/prefect-server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/datapusher"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/ckan-backend-dev/ckan"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/ckan-backend-dev/postgresql"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/ckan-backend-dev/solr"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/ckan-backend-dev/prefect-server"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/migration"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/deployment/ckan"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  - package-ecosystem: "docker"
    directory: "/deployment/frontend"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"

  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 5
    ignore:
      - dependency-name: "*"
        update-types:
          - "version-update:semver-major"
