locustfile=main.py
host=https://datasets.wri.org
users=10
spawn-rate=3
run-time=30m
print-stats=true
headless=true
html=results/report.html
csv=results/run
csv-full-history=true
json-file=results/results