FROM viderum/ckan:v2.10-dev


# Set up environment variables
ENV APP_DIR=/srv/app
ENV AWS_ACCESS_KEY_ID=minioadmin
ENV AWS_SECRET_ACCESS_KEY=minioadmin
ENV AWS_BUCKET_NAME=ckan
ENV HOST_NAME=http://minio:9000
ENV UWSGI_HARAKIRI=50
ENV CKAN_INI=${APP_DIR}/production.ini
ENV SRC_EXTENSIONS_DIR=${APP_DIR}/src_extensions

# Install any extensions needed by your CKAN instance
# - Make sure to add the plugins to CKAN__PLUGINS in the .env file
# - Also make sure all extra configuration options are added to the CKAN config file (production.ini)
#   This can be done by creating an overriding start_ckan_dev_development.sh file:
#   (https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.9/dev/setup/start_ckan_development.sh) ie: updating the 'ckan config-tool' lines
#   For more on config-tool please see https://docs.ckan.org/en/latest/maintaining/cli.html#config-tool-tool-for-editing-options-in-a-ckan-config-file
#   or using Crudini (https://github.com/pixelb/crudini) 

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime
USER root
RUN pip3 install -e 'git+https://github.com/datopian/ckanext-scheming.git@ckan-2.10#egg=ckanext-scheming' && \
    pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-scheming/ckan-2.10/test-requirements.txt' && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-s3filestore.git@wri/cost-splitting-orgs#egg=ckanext-s3filestore' && \
    pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-s3filestore/wri/cost-splitting-orgs/requirements.txt' && \
    pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-s3filestore/wri/cost-splitting-orgs/dev-requirements.txt' && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-auth.git@v2.9#egg=ckanext-auth'

COPY ../src/ckanext-wri ${APP_DIR}/src/ckanext-wri
RUN cd ${APP_DIR}/src/ckanext-wri && pip3 install -r requirements.txt && pip3 install -r dev-requirements.txt && pip3 install -e .

# Update ckanext-s3filestore test.ini with minio credentials
RUN sed -i "s|ckanext.s3filestore.aws_access_key_id = test-access-key|ckanext.s3filestore.aws_access_key_id = ${AWS_ACCESS_KEY_ID}|g" src/ckanext-s3filestore/test.ini && \
    sed -i "s|ckanext.s3filestore.aws_secret_access_key = test-secret-key|ckanext.s3filestore.aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}|g" src/ckanext-s3filestore/test.ini && \
    sed -i "s|ckanext.s3filestore.aws_bucket_name = test-bucket|ckanext.s3filestore.aws_bucket_name = ${AWS_BUCKET_NAME}|g" src/ckanext-s3filestore/test.ini && \
    sed -i "s|ckanext.s3filestore.host_name = http://127.0.0.1:9000|ckanext.s3filestore.host_name = ${HOST_NAME}|g" src/ckanext-s3filestore/test.ini

COPY scripts/run_unit_tests.sh ${APP_DIR}/run_unit_tests.sh
RUN chmod +x ${APP_DIR}/run_unit_tests.sh
RUN chown ckan:ckan ${APP_DIR}/run_unit_tests.sh

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)

COPY patches ${APP_DIR}/patches

RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done

COPY setup/prerun.py.override ${APP_DIR}/prerun.py
RUN chmod +x ${APP_DIR}/prerun.py
RUN chown ckan:ckan ${APP_DIR}/prerun.py

# Copy the entrypoint script
COPY setup/start_ckan_development.sh.override ${APP_DIR}/start_ckan_development.sh
RUN chmod +x ${APP_DIR}/start_ckan_development.sh
RUN chown ckan:ckan ${APP_DIR}/start_ckan_development.sh

COPY setup/jwtRS256.key ${APP_DIR}/jwtRS256.key
COPY setup/jwtRS256.key.pub ${APP_DIR}/jwtRS256.key.pub
RUN chown ckan:ckan ${APP_DIR}/jwtRS256.key
RUN chown ckan:ckan ${APP_DIR}/jwtRS256.key.pub

CMD ["sh", "-c", "${APP_DIR}/start_ckan_development.sh"]