FROM viderum/ckan:v2.11.0

# Set up environment variables
ENV APP_DIR=/srv/app
ENV AWS_ACCESS_KEY_ID=minioadmin
ENV AWS_SECRET_ACCESS_KEY=minioadmin
ENV AWS_BUCKET_NAME=ckan
ENV HOST_NAME=http://minio:9000
ENV UWSGI_HARAKIRI=50
ENV CKAN_INI=${APP_DIR}/production.ini
ENV SRC_EXTENSIONS_DIR=${APP_DIR}/src_extensions

# Install any extensions needed by your CKAN instance
# - Make sure to add the plugins to CKAN__PLUGINS in the .env file
# - Also make sure all extra configuration options are added to the CKAN config file (production.ini)
#   This can be done by creating an overriding start_ckan_dev_development.sh file:
#   (https://github.com/ckan/ckan-docker-base/blob/main/ckan-2.9/dev/setup/start_ckan_development.sh) ie: updating the 'ckan config-tool' lines
#   For more on config-tool please see https://docs.ckan.org/en/latest/maintaining/cli.html#config-tool-tool-for-editing-options-in-a-ckan-config-file
#   or using Crudini (https://github.com/pixelb/crudini) 

# Clone the extension(s) your are writing for your own project in the `src` folder
# to get them mounted in this image at runtime
USER root
RUN pip3 install --upgrade setuptools==70.0.0

RUN pip3 install -e 'git+https://github.com/ckan/ckanext-scheming.git@5ce30cf2856aee97fa7b49de46847f8119dad355#egg=ckanext-scheming' && \
    pip3 install -r 'https://raw.githubusercontent.com/ckan/ckanext-scheming/5ce30cf2856aee97fa7b49de46847f8119dad355/test-requirements.txt' && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-s3filestore.git@wri/cost-splitting-orgs#egg=ckanext-s3filestore' && \
    pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-s3filestore/wri/cost-splitting-orgs/requirements.txt' && \
    #pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-s3filestore/wri/cost-splitting-orgs/dev-requirements.txt' && \
    # Use latest versions for now due to build errors. TODO: Update to specific newer versions (hopefully these are compatible)
    pip3 install moto && \
    pip3 install ckanapi && \
    pip3 install httpretty && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-auth.git@okta#egg=ckanext-auth' && \
    pip3 install -r 'https://raw.githubusercontent.com/datopian/ckanext-auth/okta/requirements.txt' && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-hierarchy.git@1547962cc3f86fd008ee7ba45fd41c5afebe8ae9#egg=ckanext-hierarchy' && \
    pip3 install -e 'git+https://github.com/datopian/ckanext-issues.git@ckan-2.10#egg=ckanext-issues' && \
    # Required by ckanext-issues, but it's no longer included in any of the requirements files or the subdependencies
    pip3 install mock && \
    pip3 install -e 'git+https://github.com/ckan/ckanext-harvest.git@v1.6.0#egg=ckanext-harvest' && \
    pip3 install -r 'https://raw.githubusercontent.com/ckan/ckanext-harvest/refs/tags/v1.6.0/requirements.txt'

# Required by shapely dependency
RUN apk --update add build-base libxslt-dev python3-dev 

# Fixing security vulnerabilities
RUN apk --update add git
RUN apk add postgresql15-client
RUN apk add libpq
RUN pip install --force-reinstall -v "Pillow==11.0.0"

RUN apk add --virtual .build-deps \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing \
        --repository http://dl-cdn.alpinelinux.org/alpine/edge/main \
        gcc libc-dev geos-dev geos && \
    runDeps="$(scanelf --needed --nobanner --recursive /usr/local \
    | awk '{ gsub(/,/, "\nso:", $2); print "so:" $2 }' \
    | xargs -r apk info --installed \
    | sort -u)" && \
    apk add --virtual .rundeps $runDeps

RUN geos-config --cflags

RUN pip install --disable-pip-version-check Shapely==2.0.1

RUN apk del build-base python3-dev && \
    rm -rf /var/cache/apk/*

RUN apk add proj proj-dev proj-util musl-dev python3-dev
RUN pip3 install pyproj --no-binary pyproj
 
# Update ckanext-s3filestore test.ini with minio credentials
USER root
RUN chmod -R 777 src 
RUN chmod -R 777 ${APP_DIR}/src/
RUN chmod -R 777 ${APP_DIR}/src/*
RUN sed --version
RUN TMPDIR=/tmp sed -i "s|ckanext.s3filestore.aws_access_key_id = test-access-key|ckanext.s3filestore.aws_access_key_id = ${AWS_ACCESS_KEY_ID}|g" src/ckanext-s3filestore/test.ini && \
    TMPDIR=/tmp sed -i "s|ckanext.s3filestore.aws_secret_access_key = test-secret-key|ckanext.s3filestore.aws_secret_access_key = ${AWS_SECRET_ACCESS_KEY}|g" src/ckanext-s3filestore/test.ini && \
    TMPDIR=/tmp sed -i "s|ckanext.s3filestore.aws_bucket_name = test-bucket|ckanext.s3filestore.aws_bucket_name = ${AWS_BUCKET_NAME}|g" src/ckanext-s3filestore/test.ini && \
    TMPDIR=/tmp sed -i "s|ckanext.s3filestore.host_name = http://127.0.0.1:9000|ckanext.s3filestore.host_name = ${HOST_NAME}|g" src/ckanext-s3filestore/test.ini

RUN chmod -R 777 src

COPY scripts/run_unit_tests.sh ${APP_DIR}/run_unit_tests.sh
RUN chmod +x ${APP_DIR}/run_unit_tests.sh
RUN chown ckan:ckan ${APP_DIR}/run_unit_tests.sh

# Apply any patches needed to CKAN core or any of the built extensions (not the
# runtime mounted ones)

COPY patches ${APP_DIR}/patches

RUN apk --no-cache add patch
RUN for d in $APP_DIR/patches/*; do \
        if [ -d $d ]; then \
            for f in `ls $d/*.patch | sort -g`; do \
                cd $SRC_DIR/`basename "$d"` && echo "$0: Applying patch $f to $SRC_DIR/`basename $d`"; patch -p1 < "$f" ; \
            done ; \
        fi ; \
    done

COPY setup/prerun.py.override ${APP_DIR}/prerun.py
RUN chmod +x ${APP_DIR}/prerun.py
RUN chown ckan:ckan ${APP_DIR}/prerun.py

# Copy the entrypoint script
COPY setup/start_ckan_development.sh.override ${APP_DIR}/start_ckan_development.sh
RUN chmod +x ${APP_DIR}/start_ckan_development.sh
RUN chown ckan:ckan ${APP_DIR}/start_ckan_development.sh

RUN apk --no-cache add openssl

RUN cat ${APP_DIR}/src/ckan/requirements.txt
RUN pip3 install -r /srv/app/src/ckan/requirements.txt

RUN openssl genpkey -algorithm RSA -out ${APP_DIR}/jwtRS256.key && \
    openssl rsa -in ${APP_DIR}/jwtRS256.key -pubout -outform PEM -out ${APP_DIR}/jwtRS256.key.pub && \
    chown ckan:ckan ${APP_DIR}/jwtRS256.key && \
    chown ckan:ckan ${APP_DIR}/jwtRS256.key.pub

RUN ckan config-tool ${CKAN_INI} "api_token.jwt.algorithm = RS256" && \
    ckan config-tool ${CKAN_INI} "api_token.jwt.encode.secret = file:${APP_DIR}/jwtRS256.key" && \
    ckan config-tool ${CKAN_INI} "api_token.jwt.decode.secret = file:${APP_DIR}/jwtRS256.key.pub"


COPY docker-entrypoint.d/* /docker-entrypoint.d/

RUN ckan config-tool ${CKAN_INI} "ckan.cors.origin_allow_all = True"
RUN ckan config-tool ${CKAN_INI} "ckan.root_path = /private-admin/{{LANG}}"
RUN ckan config-tool ${CKAN_INI} -s app:main "ckan.datapusher.api_token = xxxx-xxxx-xxxx-xxxx"

COPY setup/who.ini ${APP_DIR}/src/ckan/who.ini

COPY setup/supervisord.conf /etc/supervisord.conf
COPY setup/supervisor.worker.conf /etc/supervisord.d/worker.conf
COPY setup/supervisor.harvest.conf /etc/supervisord.d/harvest.conf

RUN SUPERVISOR_USER="root"; \
    SUPERVISOR_HOME="/tmp"; \
    sed -i "s|SUPERVISOR_USER|${SUPERVISOR_USER}|g" /etc/supervisord.d/harvest.conf && \
    sed -i "s|SUPERVISOR_HOME|${SUPERVISOR_HOME}|g" /etc/supervisord.d/harvest.conf && \
    sed -i "s|SUPERVISOR_USER|${SUPERVISOR_USER}|g" /etc/supervisord.d/worker.conf && \
    sed -i "s|SUPERVISOR_HOME|${SUPERVISOR_HOME}|g" /etc/supervisord.d/worker.conf && \
    sed -i "s|SUPERVISOR_HOME|${SUPERVISOR_HOME}|g" /etc/supervisord.conf

RUN chown -R ckan:ckan /etc/supervisord.d
RUN chown -R ckan:ckan /etc/supervisord.conf

CMD ["sh", "-c", "${APP_DIR}/start_ckan_development.sh"]
