[program:ckan-fetch]
command=ckan -c /srv/app/production.ini harvester fetch-consumer
priority=501
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
<<<<<<< HEAD
user=%(ENV_SUPERVISOR_USER)s
environment=HOME="/srv/app",USER="%(ENV_SUPERVISOR_USER)s"
=======
user=SUPERVISOR_USER
environment=HOME="SUPERVISOR_HOME",USER="SUPERVISOR_USER"
>>>>>>> 5b29a5e10ef85064e84332503b6def4fa9dbce7e


[program:ckan-gather]
command=ckan -c /srv/app/production.ini harvester gather-consumer
priority=501
autostart=true
autorestart=true
redirect_stderr=true
stdout_logfile=/dev/stdout
stdout_logfile_maxbytes=0
stderr_logfile=/dev/stdout
stderr_logfile_maxbytes=0
<<<<<<< HEAD
user=%(ENV_SUPERVISOR_USER)s
environment=HOME="/srv/app",USER="%(ENV_SUPERVISOR_USER)s"
=======
user=SUPERVISOR_USER
environment=HOME="SUPERVISOR_HOME",USER="SUPERVISOR_USER"
>>>>>>> 5b29a5e10ef85064e84332503b6def4fa9dbce7e
