POST http://ckan-dev:5000/api/action/approve_pending_dataset
Content-Type: application/json
Authorization: eyJ0eXAiOiJKV1QiLCJhbGciOiJSUzI1NiJ9.eyJqdGkiOiJqeVN3UjNYaHNBbGk2djVKTl9Dbnhtck9MRHg2a0NKcnFHUzZ3WlFwVlMwIiwiaWF0IjoxNzE2MDYwODUxfQ.VOhjpMOg3Lb9CIGLgaeu5CUroZimNJRPH6Ymd9B1EI1vDlyJd5EtN9HSQZ0tnHfJVs88pIjdVj30zq0fUXf4bD7Y1jXn958Pmh8KTEo68jXNgDvLuKAQKkj8aDBrn_k4JmCSIN_1fcUX5vQEMb5ajbls9IAju_QvONIl3yC2O5Zi7bC3EM7ePcBJUTG4q31mvbUXCLqNbAtMOD3L_WJQBaYipUKTqA6mkw9jetiVD9p3_YB_BIPCilswU-i_ugyJwiCk6dFV02eGVh2UZ_XsBfpP-2irN6gUjFWvj64tDgrQA7_0P5ehNJeG7DlhEBDyy3AKG74f8AuLQbbIX6ELHg

{
    "dataset_id": "222c5a07-15df-494e-a6c4-9c38acfec9db"
}