ingress:
  enabled: true
  host:
    hostname: datasets-prefect.wri.org
    path: /
    pathType: ImplementationSpecific
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: cert-manager
  tls: true
server:
  uiConfig:
    prefectUiApiUrl: "https://datasets-prefect.wri.org/api"
  env:
  - name: PREFECT_UI_URL
    value: "https://datasets-prefect.wri.org"