name: Build and Push Frontend Image

on:
  workflow_call:
    inputs:
      branch_name:
        required: true
        type: string
  workflow_dispatch:
    inputs:
      branch_name:
        description: 'Branch name to tag (e.g., dev, staging, prod)'
        required: true
        default: 'dev'
        type: string

permissions:
  id-token: write
  contents: read

jobs:
  build-and-push-frontend:
    name: Build and Push Frontend
    runs-on: ubuntu-latest
    steps:
      - name: Git clone the repository
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.branch_name || github.ref_name }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2
        with:
          mask-password: 'true'

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push Frontend image
        uses: docker/build-push-action@v5
        env:
          REGISTRY: ${{ steps.login-ecr.outputs.registry }}
          FRONTEND_REPO: ${{ secrets.ECR_FRONTEND_REPO }}
          IMAGE_TAG: ${{ inputs.branch_name || github.ref_name }}-${{ github.sha }}
          LATEST_TAG: ${{ inputs.branch_name || github.ref_name }}-latest
        with:
          context: deployment/frontend
          file: deployment/frontend/Dockerfile
          push: true
          tags: |
            ${{ env.REGISTRY }}/${{ env.FRONTEND_REPO }}:${{ env.IMAGE_TAG }}
            ${{ github.event_name != 'pull_request' && format('{0}/{1}:{2}', env.REGISTRY, env.FRONTEND_REPO, env.LATEST_TAG) || '' }}
          build-args: |
            NEXTAUTH_SECRET="dummy-secret-for-build"
            NEXTAUTH_URL="http://localhost:3000"
            CKAN_URL="http://localhost:5000"
            NEXT_PUBLIC_CKAN_URL="http://localhost:5000"
            NEXT_PUBLIC_NEXTAUTH_URL="http://localhost:3000"
            NEXT_PUBLIC_GTM_ID="dummy-gtm-id"
            NEXT_PUBLIC_HOTJAR_ID="dummy-hotjar-id"
            NEXT_PUBLIC_GFW_API_KEY="dummy-api-key"
            OSANO_URL="http://dummy-osano-url.com"
            NEXT_PUBLIC_DEPLOYMENT_TYPE="${{ inputs.branch_name || github.ref_name }}"
          cache-from: type=gha
          cache-to: type=gha,mode=max
