name: CKAN Integration Tests using Cypress
on: push

permissions:
      id-token: write
      contents: read
jobs:
  cypress-run:
    name: Integration Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v2
        with:
          role-to-assume: ${{ secrets.OIDC_ROLE }}
          aws-region: ${{ secrets.AWS_REGION }}
      - name: Login to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v1
        with:
          mask-password: 'true'
      - name: Add url to hosts
        run: sudo echo "127.0.0.1 ckan-dev" | sudo tee -a /etc/hosts
      - name: Set up Docker Containers
        env:
          CKAN_IMAGE: '${{ steps.login-ecr.outputs.registry }}/ckan-dev-ecr:${{ github.sha }}'
        run: docker-compose up --build --image ${{ env.CKAN_IMAGE }} ckan-dev -d -f docker-compose.dev.yml --env-file .env.example
        working-directory: ./ckan-backend-dev        
      - name: Cypress Install and CKAN setup
        uses: cypress-io/github-action@v6
        continue-on-error: true
        with:
          wait-on: 'http://localhost:5000'
          wait-on-timeout: 120
          node-version: 18
          runTests: false
          continue-on-error: true
          working-directory: ./integration-tests
      - name: Curl the connection
        run: curl --request GET --url "http://ckan-dev:5000/api/action/status_show"
      - name: Create sysadmin API for Authorization
        run: bash ./ckan-backend-dev/ckan/scripts/cypress_setup.sh
      - name: Run tests 🧪
        uses: cypress-io/github-action@v6
        with:
          command: node test.js
          working-directory: ./integration-tests
      - name: Tear down containers
        if: failure() || success()
        run: docker-compose -f docker-compose.dev.yml --env-file .env.example down -v --remove-orphans
        working-directory: ./ckan-backend-dev
