name: Check Linter

on:
  pull_request:
    branches:
      - dev
    paths:
      - 'deployment/frontend/**'

jobs:
  run-ci:
    name: Linter
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'
          cache-dependency-path: 'deployment/frontend/package-lock.json'

      - name: Install dependencies
        working-directory: deployment/frontend
        run: npm ci --legacy-peer-deps

      - name: Check lint
        working-directory: deployment/frontend
        run: npm run lint:ci

